In [147]:
import datetime
from pandas import offsets
import numpy as np
import pandas as pd
from itertools import chain
import matplotlib.pyplot as plt
import re
from pandas.tseries.holiday import AbstractHolidayCalendar, Holiday, EasterMonday, Easter
from pandas.tseries.offsets import Day, DateOffset, CustomBusinessDay,CustomBusinessMonthEnd

## Упражнение 1

In [148]:
datatime = pd.read_csv('data-20191112T1252-structure-20191112T1247.csv', encoding='utf-8',usecols=[i for i in range(13)], index_col=0)
datatime

,Январь,Февраль,Март,Апрель,Май,Июнь,Июль,Август,Сентябрь,Октябрь,Ноябрь,Декабрь
Год/Месяц,,,,,,,,,,,,
1999,"1,2,3,4,6*,7,9,10,16,17,23,24,30,31","6,7,13,14,20,21,27,28","6,7,8,13,14,20,21,27,28","3,4,10,11,17,18,24,25,30*","1,2,3,4,8,9,10,15,16,22,23,29,30","5,6,11*,12,13,14,19,20,26,27","3,4,10,11,17,18,24,25,31","1,7,8,14,15,21,22,28,29","4,5,11,12,18,19,25,26","2,3,9,10,16,17,23,24,30,31","6,7,8,13,14,20,21,27,28","4,5,11,12,13,18,19,25,26,31*"
2000,"1,2,3,4,6*,7,8,9,15,16,22,23,29,30","5,6,12,13,19,20,26,27","4,5,7*,8,11,12,18,19,25,26","1,2,8,9,15,16,22,23,29,30","1,2,6,7,8*,9,13,14,20,21,27,28","3,4,10,11,12,17,18,24,25","1,2,8,9,15,16,22,23,29,30","5,6,12,13,19,20,26,27","2,3,9,10,16,17,23,24,30","1,7,8,14,15,21,22,28,29","4,5,7,11,12,18,19,25,26","2,3,9,10,11*,12,16,17,23,24,30,31"
2001,"1,2,6,7,8,13,14,20,21,27,28","3,4,10,11,17,18,24,25","3,4,7*,8,10,11,17,18,24,25,31","1,7,8,14,15,21,22,28,29,30*","1,2,5,6,8*,9,12,13,19,20,26,27","2,3,9,10,11*,12,16,17,23,24,30","1,7,8,14,15,21,22,28,29","4,5,11,12,18,19,25,26","1,2,8,9,15,16,22,23,29,30","6,7,13,14,20,21,27,28","3,4,6*,7,10,11,17,18,24,25","1,2,8,9,12,15,16,22,23,29,30"
2002,"1,2,5,6,7,12,13,19,20,26,27","2,3,9,10,16,17,22*,23,24,25","2,3,7*,8,9,10,16,17,23,24,30,31","6,7,13,14,20,21,28,30*","1,2,3,4,5,8*,9,10,11,12,19,25,26","1,2,8,9,11*,12,15,16,22,23,29,30","6,7,13,14,20,21,27,28","3,4,10,11,17,18,24,25,31","1,7,8,14,15,21,22,28,29","5,6,12,13,19,20,26,27","2,3,6*,7,8,9,16,17,23,24,30","1,7,8,11*,12,13,14,21,22,28,29,31*"
2003,"1,2,3,5*,6,7,11,12,18,19,25,26","1,2,8,9,15,16,22,23,24","1,2,7*,8,9,10,15,16,22,23,29,30","5,6,12,13,19,20,26,27,30*","1,2,3,4,8*,9,10,11,17,18,24,25,31","1,7,8,11*,12,13,14,15,22,28,29","5,6,12,13,19,20,26,27","2,3,9,10,16,17,23,24,30,31","6,7,13,14,20,21,27,28","4,5,11,12,18,19,25,26","1,2,6*,7,8,9,15,16,22,23,29,30","6,7,11*,12,13,14,20,21,27,28,31*"
2004,"1,2,3,4,6*,7,10,11,17,18,24,25,31","1,7,8,14,15,21,22,23,28,29","6,7,8,13,14,20,21,27,28","3,4,10,11,17,18,24,25,30*","1,2,3,4,8,9,10,15,16,22,23,29,30","5,6,11*,12,13,14,19,20,26,27","3,4,10,11,17,18,24,25,31","1,7,8,14,15,21,22,28,29","4,5,11,12,18,19,25,26","2,3,9,10,16,17,23,24,30,31","6,7,8,13,14,20,21,27,28","4,5,11,12,13,18,19,25,26,31*"
2005,"1,2,3,4,5,6,7,8,9,10,15,16,22,23,29,30","5,6,12,13,19,20,22*,23,26,27","5*,6,7,8,12,13,19,20,26,27","2,3,9,10,16,17,23,24,30","1,2,7,8,9,14,15,21,22,28,29","4,5,11,12,13,18,19,25,26","2,3,9,10,16,17,23,24,30,31","6,7,13,14,20,21,27,28","3,4,10,11,17,18,24,25","1,2,8,9,15,16,22,23,29,30","3*,4,5,6,12,13,19,20,26,27","3,4,10,11,17,18,24,25,31"
2006,"1,2,3,4,5,6,7,8,9,14,15,21,22,28,29","4,5,11,12,18,19,22*,23,24,25","4,5,7*,8,11,12,18,19,25,26","1,2,8,9,15,16,22,23,29,30","1,6*,7,8,9,13,14,20,21,27,28","3,4,10,11,12,17,18,24,25","1,2,8,9,15,16,22,23,29,30","5,6,12,13,19,20,26,27","2,3,9,10,16,17,23,24,30","1,7,8,14,15,21,22,28,29","3*,4,5,6,11,12,18,19,25,26","2,3,9,10,16,17,23,24,30,31"
2007,"1,2,3,4,5,6,7,8,13,14,20,21,27,28","3,4,10,11,17,18,22*,23,24,25","3,4,7*,8,10,11,17,18,24,25,31","1,7,8,14,15,21,22,28*,29,30","1,5,6,8*,9,12,13,19,20,26,27","2,3,9*,10,11,12,16,17,23,24,30","1,7,8,14,15,21,22,28,29","4,5,11,12,18,19,25,26","1,2,8,9,15,16,22,23,29,30","6,7,13,14,20,21,27,28","3,4,5,10,11,17,18,24,25","1,2,8,9,15,16,22,23,29*,30,31"
2008,"1,2,3,4,5,6,7,8,12,13,19,20,26,27","2,3,9,10,16,17,22*,23,24,25","1,2,7*,8,9,10,15,16,22,23,29,30","5,6,12,13,19,20,26,27,30*","1,2,3,8*,9,10,11,17,18,24,25,31","1,8,11*,12,13,14,15,21,22,28,29","5,6,12,13,19,20,26,27","2,3,9,10,16,17,23,24,30,31","6,7,13,14,20,21,27,28","4,5,11,12,18,19,25,26","1*,2,3,4,8,9,15,16,22,23,29,30","6,7,13,14,20,21,27,28,31*"
2009,"1,2,3,4,5,6,7,8,9,10,17,18,24,25,31","1,7,8,14,15,21,22,23,28","1,7,8,9,14,15,21,22,28,29","4,5,11,12,18,19,25,26","1,2,3,8*,9,10,11,16,17,23,24,30,31","6,7,11*,12,13,14,20,21,27,28","4,5,11,12,18,19,25,26","1,2,8,9,15,16,22,23,29,30","5,6,12,13,19,20,26,27","3,4,10,11,17,18,24,25,31","1,3*,4,7,8,14,15,21,22,28,29","5,6,12,13,19,20,26,27,31*"
2010,"1,2,3,4,5,6,7,8,9,10,16,17,23,24,30,31","6,7,13,14,20,21,22,23,27*,28","6,7,8,13,14,20,21,27,28","3,4,10,11,17,18,24,25,30*","1,2,3,8,9,10,15,16,22,23,29,30","5,6,11*,12,13,14,19,20,26,27","3,4,10,11,17,18,24,25,31","1,7,8,14,15,21,22,28,29","4,5,11,12,18,19,25,26","2,3,9,10,16,17,23,24,30,31","3*,4,5,6,7,14,20,21,27,28","4,5,11,12,18,19,25,26,31*"
2011,"1,2,3,4,5,6,7,8,9,10,15,16,22,23,29,30","5,6,12,13,19,20,22*,23,26,27","5*,6,7,8,12,13,19,20,26,27","2,3,9,10,16,17,23,24,30","1,2,7,8,9,14,15,21,22,28,29","4,5,11,12,13,18,19,25,26","2,3,9,10,16,17,23,24,30,31","6,7,13,14,20,21,27,28","3,4,10,11,17,18,24,25","1,2,8,9,15,16,22,23,29,30","3*,4,5,6,12,13,19,20,26,27","3,4,10,11,17,18,24,25,31"
2012,"1,2,3,4,5,6,7,8,9,14,15,21,22,28,29","4,5,11,12,18,19,22*,23,25,26","3,4,7*,8,9,10,17,18,24,25,31","1,7,8,14,15,21,22,28*,29,30","1,6,7,8,9,12*,13,19,20,26,27","2,3,9*,10,11,12,16,17,23,24,30","1,7,8,14,15,21,22,28,29","4,5,11,12,18,19,25,26","1,2,8,9,15,16,22,23,29,30","6,7,13,14,20,21,27,28","3,4,5,10,11,17,18,24,25","1,2,8,9,15,16,22,23,29*,30,31"
2013,"1,2,3,4,5,6,7,8,12,13,19,20,26,27","2,3,9,10,16,17,22*,23,24","2,3,7*,8,9,10,16,17,23,24,30,31","6,7,13,14,20,21,27,28","1,2,3,4,5,8*,9,10,11,12,18,19,25,26","1,2,8,9,11*,12,15,16,22,23,29,30","6,7,13,14,20,21,27,28","3,4,10,11,17,18,24,25,31","1,7,8,14,15,21,22,28,29","5,6,12,13,19,20,26,27","2,3,4,9,10,16,17,23,24,30","1,7,8,14,15,21,22,28,29,31*"
2014,"1,2,3,4,5,6,7,8,11,12,18,19,25,26","1,2,8,9,15,16,22,23,24*","1,2,7*,8,9,10,15,16,22,23,29,30","5,6,12,13,19,20,26,27,30*","1,2,3,4,8*,9,10,11,17,18,24,25,31","1,7,8,11*,12,13,14,15,21,22,28,29","5,6,12,13,19,20,26,27","2,3,9,10,16,17,23,24,30,31","6,7,13,14,20,21,27,28","4,5,11,12,18,19,25,26","1,2,3,4,8,9,15,16,22,23,29,30","6,7,13,14,20,21,27,28"
2015,"1,2,3,4,5,6,7,8,9,10,11,17,18,24,25,31","1,7,8,14,15,21,22,23,28","1,7,8,9,14,15,21,22,28,29","4,5,11,12,18,19,25,26,30*","1,2,3,4,8*,9,10,11,16,17,23,24,30,31","6,7,11*,12,13,14,20,21,27,28","4,5,11,12,18,19,25,26","1,2,8,9,15,16,22,23,29,30","5,6,12,13,19,20,26,27","3,4,10,11,17,18,24,25,31","1,3*,4,7,8,14,15,21,22,28,29","5,6,12,13,19,20,26,27,31*"
2016,"1,2,3,4,5,6,7,8,9,10,16,17,23,24,30,31","6,7,13,14,20*,21,22,23,27,28","5,6,7,8,12,13,19,20,26,27","2,3,9,10,16,17,23,24,30","1,2,3,7,8,9,14,15,21,22,28,29","4,5,11,12,13,18,19,25,26","2,3,9,10,16,17,23,24,30,31","6,7,13,14,20,21,27,28","3,4,10,11,17,18,24,25","1,2,8,9,15,16,22,23,29,30","3*,4,5,6,12,13,19,20,26,27","3,4,10,11,17,18,24,25,31"
2017,"1,2,3,4,5,6,7,8,14,15,21,22,28,29","4,5,11,12,18,19,22*,23,24,25,26","4,5,7*,8,11,12,18,19,25,26","1,2,8,9,15,16,22,23,29,30","1,6,7,8,9,13,14,20,21,27,28","3,4,10,11,12,17,18,24,25","1,2,8,9,15,16,22,23,29,30","5,6,12,13,19,20,26,27","2,3,9,10,16,17,23,24,30","1,7,8,14,15,21,22,28,29","3*,4,5,6,11,12,18,19,25,26","2,3,9,10,16,17,23,24,30,31"
2018,"1,2,3,4,5,6,7,8,13,14,20,21,27,28","3,4,10,11,17,18,22*,23,24,25","3,4,7*,8,9,10,11,17,18,24,25,31","1,7,8,14,15,21,22,28*,29,30","1,2,5,6,8*,9,12,13,19,20,26,27","2,3,9*,10,11,12,16,17,23,24,30","1,7,8,14,15,21,22,28,29","4,5,11,12,18,19,25,26","1,2,8,9,15,16,22,23,29,30","6,7,13,14,20,21,27,28","3,4,5,10,11,17,18,24,25","1,2,8,9,15,16,22,23,29*,30,31"
2019,"1,2,3,4,5,6,7,8,12,13,19,20,26,27","2,3,9,10,16,17,22*,23,24","2,3,7*,8,9,10,16,17,23,24,30,31","6,7,13,14,20,21,27,28,30*","1,2,3,4,5,8*,9,10,11,12,18,19,25,26","1,2,8,9,11*,12,15,16,22,23,29,30","6,7,13,14,20,21,27,28","3,4,10,11,17,18,24,25,31","1,7,8,14,15,21,22,28,29","5,6,12,13,19,20,26,27","2,3,4,9,10,16,17,23,24,30","1,7,8,14,15,21,22,28,29,31*"
2020,"1,2,3,4,5,6,7,8,11,12,18,19,25,26","1,2,8,9,15,16,22,23,24+,29","1,7,8,9+,14,15,21,22,28,29","4,5,11,12,18,19,25,26,30*","1,2,3,4+,5+,8*,9,10,11+,16,17,23,24,30,31","6,7,11*,12,13,14,20,21,27,28","4,5,11,12,18,19,25,26","1,2,8,9,15,16,22,23,29,30","5,6,12,13,19,20,26,27","3,4,10,11,17,18,24,25,31","1,3*,4,7,8,14,15,21,22,28,29","5,6,12,13,19,20,26,27,31*"
2021,"1,2,3,4,5,6,7,8,9,10,16,17,23,24,30,31","6,7,13,14,20,21,22*,23,27,28","6,7,8*,13,14,20,21,27,28","3,4,10,11,17,18,24,25,30*","1,2,3+,8,9,10+,15,16,22,23,29,30","5,6,11*,12,13,14+,19,20,26,27","3,4,10,11,17,18,24,25,31","1,7,8,14,15,21,22,28,29","4,5,11,12,18,19,25,26","2,3,9,10,16,17,23,24,30,31","3*,4,6,7,13,14,20,21,27,28","4,5,11,12,18,19,25,26,31*"
2022,"1,2,3,4,5,6,7,8,9,15,16,22,23,29,30","5,6,12,13,19,20,22*,23,26,27","5,6,7*,8,12,13,19,20,26,27","2,3,9,10,16,17,23,24,30","1,2+,7,8,9,14,15,21,22,28,29","4,5,11,12,13+,18,19,25,26","2,3,9,10,16,17,23,24,30,31","6,7,13,14,20,21,27,28","3,4,10,11,17,18,24,25","1,2,8,9,15,16,22,23,29,30","3*,4,5,6,12,13,19,20,26,27","3,4,10,11,17,18,24,25,31"
2023,"1,2,3,4,5,6,7,8,14,15,21,22,28,29","4,5,11,12,18,19,22*,23,25,26","4,5,7*,8,11,12,18,19,25,26","1,2,8,9,15,16,22,23,29,30","1,6,7,8*,9,13,14,20,21,27,28","3,4,10,11,12,17,18,24,25","1,2,8,9,15,16,22,23,29,30","5,6,12,13,19,20,26,27","2,3,9,10,16,17,23,24,30","1,7,8,14,15,21,22,28,29","3*,4,5,6+,11,12,18,19,25,26","2,3,9,10,16,17,23,24,30,31"
2024,"1,2,3,4,5,6,7,8,13,14,20,21,27,28","3,4,10,11,17,18,22*,23,24,25","2,3,7*,8,9,10,16,17,23,24,30,31","6,7,13,14,20,21,27,28,30*","1,4,5,8*,9,11,12,18,19,25,26","1,2,8,9,11*,12,15,16,22,23,29,30","6,7,13,14,20,21,27,28","3,4,10,11,17,18,24,25,31","1,7,8,14,15,21,22,28,29","5,6,12,13,19,20,26,27","2,3,4,9,10,16,17,23,24,30","1,7,8,14,15,21,22,28,29,31*"
2025,"1,2,3,4,5,6,7,8,11,12,18,19,25,26","1,2,8,9,15,16,22,23,24+","1,2,7*,8,9,10+,15,16,22,23,29,30","5,6,12,13,19,20,26,27,30*","1,3,4,8*,9,10,11,17,18,24,25,31","1,7,8,11*,12,14,15,21,22,28,29","5,6,12,13,19,20,26,27","2,3,9,10,16,17,23,24,30,31","6,7,13,14,20,21,27,28","4,5,11,12,18,19,25,26","1,2,3*,4,8,9,15,16,22,23,29,30","6,7,13,14,20,21,27,28,31*"

In [149]:
df_1=datatime.applymap(lambda x: x.split(','))
df_1=datatime.columns = np.arange(1,13)
datatime

,1,2,3,4,5,6,7,8,9,10,11,12
Год/Месяц,,,,,,,,,,,,
1999,"1,2,3,4,6*,7,9,10,16,17,23,24,30,31","6,7,13,14,20,21,27,28","6,7,8,13,14,20,21,27,28","3,4,10,11,17,18,24,25,30*","1,2,3,4,8,9,10,15,16,22,23,29,30","5,6,11*,12,13,14,19,20,26,27","3,4,10,11,17,18,24,25,31","1,7,8,14,15,21,22,28,29","4,5,11,12,18,19,25,26","2,3,9,10,16,17,23,24,30,31","6,7,8,13,14,20,21,27,28","4,5,11,12,13,18,19,25,26,31*"
2000,"1,2,3,4,6*,7,8,9,15,16,22,23,29,30","5,6,12,13,19,20,26,27","4,5,7*,8,11,12,18,19,25,26","1,2,8,9,15,16,22,23,29,30","1,2,6,7,8*,9,13,14,20,21,27,28","3,4,10,11,12,17,18,24,25","1,2,8,9,15,16,22,23,29,30","5,6,12,13,19,20,26,27","2,3,9,10,16,17,23,24,30","1,7,8,14,15,21,22,28,29","4,5,7,11,12,18,19,25,26","2,3,9,10,11*,12,16,17,23,24,30,31"
2001,"1,2,6,7,8,13,14,20,21,27,28","3,4,10,11,17,18,24,25","3,4,7*,8,10,11,17,18,24,25,31","1,7,8,14,15,21,22,28,29,30*","1,2,5,6,8*,9,12,13,19,20,26,27","2,3,9,10,11*,12,16,17,23,24,30","1,7,8,14,15,21,22,28,29","4,5,11,12,18,19,25,26","1,2,8,9,15,16,22,23,29,30","6,7,13,14,20,21,27,28","3,4,6*,7,10,11,17,18,24,25","1,2,8,9,12,15,16,22,23,29,30"
2002,"1,2,5,6,7,12,13,19,20,26,27","2,3,9,10,16,17,22*,23,24,25","2,3,7*,8,9,10,16,17,23,24,30,31","6,7,13,14,20,21,28,30*","1,2,3,4,5,8*,9,10,11,12,19,25,26","1,2,8,9,11*,12,15,16,22,23,29,30","6,7,13,14,20,21,27,28","3,4,10,11,17,18,24,25,31","1,7,8,14,15,21,22,28,29","5,6,12,13,19,20,26,27","2,3,6*,7,8,9,16,17,23,24,30","1,7,8,11*,12,13,14,21,22,28,29,31*"
2003,"1,2,3,5*,6,7,11,12,18,19,25,26","1,2,8,9,15,16,22,23,24","1,2,7*,8,9,10,15,16,22,23,29,30","5,6,12,13,19,20,26,27,30*","1,2,3,4,8*,9,10,11,17,18,24,25,31","1,7,8,11*,12,13,14,15,22,28,29","5,6,12,13,19,20,26,27","2,3,9,10,16,17,23,24,30,31","6,7,13,14,20,21,27,28","4,5,11,12,18,19,25,26","1,2,6*,7,8,9,15,16,22,23,29,30","6,7,11*,12,13,14,20,21,27,28,31*"
2004,"1,2,3,4,6*,7,10,11,17,18,24,25,31","1,7,8,14,15,21,22,23,28,29","6,7,8,13,14,20,21,27,28","3,4,10,11,17,18,24,25,30*","1,2,3,4,8,9,10,15,16,22,23,29,30","5,6,11*,12,13,14,19,20,26,27","3,4,10,11,17,18,24,25,31","1,7,8,14,15,21,22,28,29","4,5,11,12,18,19,25,26","2,3,9,10,16,17,23,24,30,31","6,7,8,13,14,20,21,27,28","4,5,11,12,13,18,19,25,26,31*"
2005,"1,2,3,4,5,6,7,8,9,10,15,16,22,23,29,30","5,6,12,13,19,20,22*,23,26,27","5*,6,7,8,12,13,19,20,26,27","2,3,9,10,16,17,23,24,30","1,2,7,8,9,14,15,21,22,28,29","4,5,11,12,13,18,19,25,26","2,3,9,10,16,17,23,24,30,31","6,7,13,14,20,21,27,28","3,4,10,11,17,18,24,25","1,2,8,9,15,16,22,23,29,30","3*,4,5,6,12,13,19,20,26,27","3,4,10,11,17,18,24,25,31"
2006,"1,2,3,4,5,6,7,8,9,14,15,21,22,28,29","4,5,11,12,18,19,22*,23,24,25","4,5,7*,8,11,12,18,19,25,26","1,2,8,9,15,16,22,23,29,30","1,6*,7,8,9,13,14,20,21,27,28","3,4,10,11,12,17,18,24,25","1,2,8,9,15,16,22,23,29,30","5,6,12,13,19,20,26,27","2,3,9,10,16,17,23,24,30","1,7,8,14,15,21,22,28,29","3*,4,5,6,11,12,18,19,25,26","2,3,9,10,16,17,23,24,30,31"
2007,"1,2,3,4,5,6,7,8,13,14,20,21,27,28","3,4,10,11,17,18,22*,23,24,25","3,4,7*,8,10,11,17,18,24,25,31","1,7,8,14,15,21,22,28*,29,30","1,5,6,8*,9,12,13,19,20,26,27","2,3,9*,10,11,12,16,17,23,24,30","1,7,8,14,15,21,22,28,29","4,5,11,12,18,19,25,26","1,2,8,9,15,16,22,23,29,30","6,7,13,14,20,21,27,28","3,4,5,10,11,17,18,24,25","1,2,8,9,15,16,22,23,29*,30,31"
2008,"1,2,3,4,5,6,7,8,12,13,19,20,26,27","2,3,9,10,16,17,22*,23,24,25","1,2,7*,8,9,10,15,16,22,23,29,30","5,6,12,13,19,20,26,27,30*","1,2,3,8*,9,10,11,17,18,24,25,31","1,8,11*,12,13,14,15,21,22,28,29","5,6,12,13,19,20,26,27","2,3,9,10,16,17,23,24,30,31","6,7,13,14,20,21,27,28","4,5,11,12,18,19,25,26","1*,2,3,4,8,9,15,16,22,23,29,30","6,7,13,14,20,21,27,28,31*"
2009,"1,2,3,4,5,6,7,8,9,10,17,18,24,25,31","1,7,8,14,15,21,22,23,28","1,7,8,9,14,15,21,22,28,29","4,5,11,12,18,19,25,26","1,2,3,8*,9,10,11,16,17,23,24,30,31","6,7,11*,12,13,14,20,21,27,28","4,5,11,12,18,19,25,26","1,2,8,9,15,16,22,23,29,30","5,6,12,13,19,20,26,27","3,4,10,11,17,18,24,25,31","1,3*,4,7,8,14,15,21,22,28,29","5,6,12,13,19,20,26,27,31*"
2010,"1,2,3,4,5,6,7,8,9,10,16,17,23,24,30,31","6,7,13,14,20,21,22,23,27*,28","6,7,8,13,14,20,21,27,28","3,4,10,11,17,18,24,25,30*","1,2,3,8,9,10,15,16,22,23,29,30","5,6,11*,12,13,14,19,20,26,27","3,4,10,11,17,18,24,25,31","1,7,8,14,15,21,22,28,29","4,5,11,12,18,19,25,26","2,3,9,10,16,17,23,24,30,31","3*,4,5,6,7,14,20,21,27,28","4,5,11,12,18,19,25,26,31*"
2011,"1,2,3,4,5,6,7,8,9,10,15,16,22,23,29,30","5,6,12,13,19,20,22*,23,26,27","5*,6,7,8,12,13,19,20,26,27","2,3,9,10,16,17,23,24,30","1,2,7,8,9,14,15,21,22,28,29","4,5,11,12,13,18,19,25,26","2,3,9,10,16,17,23,24,30,31","6,7,13,14,20,21,27,28","3,4,10,11,17,18,24,25","1,2,8,9,15,16,22,23,29,30","3*,4,5,6,12,13,19,20,26,27","3,4,10,11,17,18,24,25,31"
2012,"1,2,3,4,5,6,7,8,9,14,15,21,22,28,29","4,5,11,12,18,19,22*,23,25,26","3,4,7*,8,9,10,17,18,24,25,31","1,7,8,14,15,21,22,28*,29,30","1,6,7,8,9,12*,13,19,20,26,27","2,3,9*,10,11,12,16,17,23,24,30","1,7,8,14,15,21,22,28,29","4,5,11,12,18,19,25,26","1,2,8,9,15,16,22,23,29,30","6,7,13,14,20,21,27,28","3,4,5,10,11,17,18,24,25","1,2,8,9,15,16,22,23,29*,30,31"
2013,"1,2,3,4,5,6,7,8,12,13,19,20,26,27","2,3,9,10,16,17,22*,23,24","2,3,7*,8,9,10,16,17,23,24,30,31","6,7,13,14,20,21,27,28","1,2,3,4,5,8*,9,10,11,12,18,19,25,26","1,2,8,9,11*,12,15,16,22,23,29,30","6,7,13,14,20,21,27,28","3,4,10,11,17,18,24,25,31","1,7,8,14,15,21,22,28,29","5,6,12,13,19,20,26,27","2,3,4,9,10,16,17,23,24,30","1,7,8,14,15,21,22,28,29,31*"
2014,"1,2,3,4,5,6,7,8,11,12,18,19,25,26","1,2,8,9,15,16,22,23,24*","1,2,7*,8,9,10,15,16,22,23,29,30","5,6,12,13,19,20,26,27,30*","1,2,3,4,8*,9,10,11,17,18,24,25,31","1,7,8,11*,12,13,14,15,21,22,28,29","5,6,12,13,19,20,26,27","2,3,9,10,16,17,23,24,30,31","6,7,13,14,20,21,27,28","4,5,11,12,18,19,25,26","1,2,3,4,8,9,15,16,22,23,29,30","6,7,13,14,20,21,27,28"
2015,"1,2,3,4,5,6,7,8,9,10,11,17,18,24,25,31","1,7,8,14,15,21,22,23,28","1,7,8,9,14,15,21,22,28,29","4,5,11,12,18,19,25,26,30*","1,2,3,4,8*,9,10,11,16,17,23,24,30,31","6,7,11*,12,13,14,20,21,27,28","4,5,11,12,18,19,25,26","1,2,8,9,15,16,22,23,29,30","5,6,12,13,19,20,26,27","3,4,10,11,17,18,24,25,31","1,3*,4,7,8,14,15,21,22,28,29","5,6,12,13,19,20,26,27,31*"
2016,"1,2,3,4,5,6,7,8,9,10,16,17,23,24,30,31","6,7,13,14,20*,21,22,23,27,28","5,6,7,8,12,13,19,20,26,27","2,3,9,10,16,17,23,24,30","1,2,3,7,8,9,14,15,21,22,28,29","4,5,11,12,13,18,19,25,26","2,3,9,10,16,17,23,24,30,31","6,7,13,14,20,21,27,28","3,4,10,11,17,18,24,25","1,2,8,9,15,16,22,23,29,30","3*,4,5,6,12,13,19,20,26,27","3,4,10,11,17,18,24,25,31"
2017,"1,2,3,4,5,6,7,8,14,15,21,22,28,29","4,5,11,12,18,19,22*,23,24,25,26","4,5,7*,8,11,12,18,19,25,26","1,2,8,9,15,16,22,23,29,30","1,6,7,8,9,13,14,20,21,27,28","3,4,10,11,12,17,18,24,25","1,2,8,9,15,16,22,23,29,30","5,6,12,13,19,20,26,27","2,3,9,10,16,17,23,24,30","1,7,8,14,15,21,22,28,29","3*,4,5,6,11,12,18,19,25,26","2,3,9,10,16,17,23,24,30,31"
2018,"1,2,3,4,5,6,7,8,13,14,20,21,27,28","3,4,10,11,17,18,22*,23,24,25","3,4,7*,8,9,10,11,17,18,24,25,31","1,7,8,14,15,21,22,28*,29,30","1,2,5,6,8*,9,12,13,19,20,26,27","2,3,9*,10,11,12,16,17,23,24,30","1,7,8,14,15,21,22,28,29","4,5,11,12,18,19,25,26","1,2,8,9,15,16,22,23,29,30","6,7,13,14,20,21,27,28","3,4,5,10,11,17,18,24,25","1,2,8,9,15,16,22,23,29*,30,31"
2019,"1,2,3,4,5,6,7,8,12,13,19,20,26,27","2,3,9,10,16,17,22*,23,24","2,3,7*,8,9,10,16,17,23,24,30,31","6,7,13,14,20,21,27,28,30*","1,2,3,4,5,8*,9,10,11,12,18,19,25,26","1,2,8,9,11*,12,15,16,22,23,29,30","6,7,13,14,20,21,27,28","3,4,10,11,17,18,24,25,31","1,7,8,14,15,21,22,28,29","5,6,12,13,19,20,26,27","2,3,4,9,10,16,17,23,24,30","1,7,8,14,15,21,22,28,29,31*"
2020,"1,2,3,4,5,6,7,8,11,12,18,19,25,26","1,2,8,9,15,16,22,23,24+,29","1,7,8,9+,14,15,21,22,28,29","4,5,11,12,18,19,25,26,30*","1,2,3,4+,5+,8*,9,10,11+,16,17,23,24,30,31","6,7,11*,12,13,14,20,21,27,28","4,5,11,12,18,19,25,26","1,2,8,9,15,16,22,23,29,30","5,6,12,13,19,20,26,27","3,4,10,11,17,18,24,25,31","1,3*,4,7,8,14,15,21,22,28,29","5,6,12,13,19,20,26,27,31*"
2021,"1,2,3,4,5,6,7,8,9,10,16,17,23,24,30,31","6,7,13,14,20,21,22*,23,27,28","6,7,8*,13,14,20,21,27,28","3,4,10,11,17,18,24,25,30*","1,2,3+,8,9,10+,15,16,22,23,29,30","5,6,11*,12,13,14+,19,20,26,27","3,4,10,11,17,18,24,25,31","1,7,8,14,15,21,22,28,29","4,5,11,12,18,19,25,26","2,3,9,10,16,17,23,24,30,31","3*,4,6,7,13,14,20,21,27,28","4,5,11,12,18,19,25,26,31*"
2022,"1,2,3,4,5,6,7,8,9,15,16,22,23,29,30","5,6,12,13,19,20,22*,23,26,27","5,6,7*,8,12,13,19,20,26,27","2,3,9,10,16,17,23,24,30","1,2+,7,8,9,14,15,21,22,28,29","4,5,11,12,13+,18,19,25,26","2,3,9,10,16,17,23,24,30,31","6,7,13,14,20,21,27,28","3,4,10,11,17,18,24,25","1,2,8,9,15,16,22,23,29,30","3*,4,5,6,12,13,19,20,26,27","3,4,10,11,17,18,24,25,31"
2023,"1,2,3,4,5,6,7,8,14,15,21,22,28,29","4,5,11,12,18,19,22*,23,25,26","4,5,7*,8,11,12,18,19,25,26","1,2,8,9,15,16,22,23,29,30","1,6,7,8*,9,13,14,20,21,27,28","3,4,10,11,12,17,18,24,25","1,2,8,9,15,16,22,23,29,30","5,6,12,13,19,20,26,27","2,3,9,10,16,17,23,24,30","1,7,8,14,15,21,22,28,29","3*,4,5,6+,11,12,18,19,25,26","2,3,9,10,16,17,23,24,30,31"
2024,"1,2,3,4,5,6,7,8,13,14,20,21,27,28","3,4,10,11,17,18,22*,23,24,25","2,3,7*,8,9,10,16,17,23,24,30,31","6,7,13,14,20,21,27,28,30*","1,4,5,8*,9,11,12,18,19,25,26","1,2,8,9,11*,12,15,16,22,23,29,30","6,7,13,14,20,21,27,28","3,4,10,11,17,18,24,25,31","1,7,8,14,15,21,22,28,29","5,6,12,13,19,20,26,27","2,3,4,9,10,16,17,23,24,30","1,7,8,14,15,21,22,28,29,31*"
2025,"1,2,3,4,5,6,7,8,11,12,18,19,25,26","1,2,8,9,15,16,22,23,24+","1,2,7*,8,9,10+,15,16,22,23,29,30","5,6,12,13,19,20,26,27,30*","1,3,4,8*,9,10,11,17,18,24,25,31","1,7,8,11*,12,14,15,21,22,28,29","5,6,12,13,19,20,26,27","2,3,9,10,16,17,23,24,30,31","6,7,13,14,20,21,27,28","4,5,11,12,18,19,25,26","1,2,3*,4,8,9,15,16,22,23,29,30","6,7,13,14,20,21,27,28,31*"

In [159]:
#Три датафрейма (три категории дат соответственно)
def before_holidays_0(dates): 
    l = [int(d[:-1]) for d in dates if d.endswith('*')]
    return l if len(l) else [None]

def new_holidays_0(dates): 
    l = [int(d[:-1]) for d in dates if d.endswith('+')]
    return l if len(l) else [None]

def weekends_0(dates):
    return [int(d) for d in dates if not d.endswith('*') and not d.endswith('+')]


before_holidays = df_1.applymap(before_holidays_0)
new_holidays = df_1.applymap(new_holidays_0)
weekends = df_1.applymap(weekends_0)

before_holidays

AttributeError: 'numpy.ndarray' object has no attribute 'applymap'

In [151]:
before_holidays = list(filter(None, [pd.Timestamp(year, month, day)
                           if day is not None else None
                           for year in before_holidays.index
                           for month in before_holidays.columns
                           for day in before_holidays.loc[year][month]]))

new_holidays = [Holiday(name='Shifted_holiday', year=year, month=month, day=day)
        if day is not None else None
        for year in new_holidays.index
        for month in new_holidays.columns
        for day in new_holidays.loc[year][month]]

weekends = [Holiday(name='Weekend or Holiday', year=year, month=month, day=day)
        if day is not None else None
        for year in weekends.index
        for month in weekends.columns
        for day in weekends.loc[year][month]]

rules = list(filter(None, [*weekends, *new_holidays]))

TypeError: 'builtin_function_or_method' object is not iterable

In [152]:
# Создание календаря
class RussianBusinessCalendar(AbstractHolidayCalendar):
    start_date = datetime.datetime(1999, 1, 1)
    end_date = datetime.datetime(2025, 12, 31)
    rules = rules

russian_calendar = CustomBusinessDay(calendar=RussianBusinessCalendar())

business_month_ends = CustomBusinessMonthEnd(holidays=rules)

In [161]:
monthes = ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь',
           'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь']
weekdays = ['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Вс']
d_types = ['Выходной', 'Праздник', 'Предпраздничный рабочий день',
           'Последний день месяца', 'Последний рабочий день месяца']
cols = [*d_types, *weekdays, *monthes, 'Предновогодний выходной день']

Work_calendar = pd.DataFrame(columns=cols, index=pd.date_range(start='1999-01-01', end='2025-12-31', freq='D'))
Work_calendar = custom_calendar.fillna(0)

In [154]:
holiday_dates = [*['1999-01-0{}'.format(i) for i in range(1, 9)], '1999-02-23', '1999-03-08', '1999-05-01','1999-05-09', 
                 '1999-06-12', '1999-11-04']
official_holidays = [pd.date_range(start=d, end='2025-12-31', freq=DateOffset(years=1)) for d in holiday_dates]
official_holidays = list(chain(*official_holidays))
new_year_eves = pd.date_range(start='2000-12-31', end='2025-12-31', freq=DateOffset(years=1))
bus_month_ends = pd.date_range(start='1999-01-01', end='2025-12-31', freq=business_month_ends)

In [155]:
Work_calendar.loc[russian_calendar.holidays, ['выходной']] = 1
Work_calendar.loc[official_holidays, ['праздник']] = 1
Work_calendar.loc[official_holidays, ['выходной']] = 1
Work_calendar.loc[new_year_eves, ['Предновогодний выходной день']] = 1
Work_calendar.loc[custom_calendar.index.is_month_end == True, ['последний день месяца']] = 1
Work_calendar.loc[bus_month_ends, ['последний рабочий день месяца']] = 1
Work_calendar.loc[before_holidays, ['предпраздничный рабочий день']] = 1

for i, v in enumerate(m_names):
    Work_calendar.loc[Work_calendar.index.month == i+1, [v]] = 1

for i, v in enumerate(wd_names):
    Work_calendar.loc[Work_calendar.index.dayofweek == i, [v]] = 1

In [162]:
Work_calendar

,выходной,праздник,предпраздничный рабочий день,последний день месяца,последний рабочий день месяца,пн,вт,ср,чт,пт,...,апрель,май,июнь,июль,август,сентябрь,октябрь,ноябрь,декабрь,Предновогодний выходной день
1999-01-01,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1999-01-02,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1999-01-03,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1999-01-04,1,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1999-01-05,1,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-12-27,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2025-12-28,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2025-12-29,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2025-12-30,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2025-12-31,0,0,1,1,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,1

## Задание 2

In [165]:
data = pd.read_csv('sber_stocks.csv', usecols=['CLOSE', 'TRADEDATE'], 
                 index_col='TRADEDATE', parse_dates=True)
data = data.CLOSE

In [166]:
data_1 = data.asfreq(pd.offsets.Day()).fillna(method='ffill')
data_1

TRADEDATE
2013-03-25     98.79
2013-03-26     97.20
2013-03-27     96.75
2013-03-28     98.59
2013-03-29     98.76
               ...
2020-01-06    253.90
2020-01-07    253.90
2020-01-08    259.15
2020-01-09    257.99
2020-01-10    258.19
Freq: D, Name: CLOSE, Length: 2483, dtype: float64

In [167]:
data_2 = pd.DataFrame(data_1)
data_2['weekday'] = data_2.index.weekday
data_2

             CLOSE  weekday
TRADEDATE
2013-03-25   98.79        0
2013-03-26   97.20        1
2013-03-27   96.75        2
2013-03-28   98.59        3
2013-03-29   98.76        4
...            ...      ...
2020-01-06  253.90        0
2020-01-07  253.90        1
2020-01-08  259.15        2
2020-01-09  257.99        3
2020-01-10  258.19        4

[2483 rows x 2 columns]

In [169]:
for i in range(1, 6, 2):
    data_2['Лаг ' + str(i)]=data_1.shift(i, freq=russian_calendar).values
data_2

C:\Users\David\anaconda3\lib\site-packages\pandas\core\arrays\datetimes.py:692: PerformanceWarning: Non-vectorized DateOffset being applied to Series or DatetimeIndex
  warnings.warn(

             CLOSE  weekday    Лаг1    Лаг3    Лаг5   Лаг 1   Лаг 3   Лаг 5
TRADEDATE
2013-03-25   98.79        0   98.79   98.79   98.79   98.79   98.79   98.79
2013-03-26   97.20        1   97.20   97.20   97.20   97.20   97.20   97.20
2013-03-27   96.75        2   96.75   96.75   96.75   96.75   96.75   96.75
2013-03-28   98.59        3   98.59   98.59   98.59   98.59   98.59   98.59
2013-03-29   98.76        4   98.76   98.76   98.76   98.76   98.76   98.76
...            ...      ...     ...     ...     ...     ...     ...     ...
2020-01-06  253.90        0  253.90  253.90  253.90  253.90  253.90  253.90
2020-01-07  253.90        1  253.90  253.90  253.90  253.90  253.90  253.90
2020-01-08  259.15        2  259.15  259.15  259.15  259.15  259.15  259.15
2020-01-09  257.99        3  257.99  257.99  257.99  257.99  257.99  257.99
2020-01-10  258.19        4  258.19  258.19  258.19  258.19  258.19  258.19

[2483 rows x 8 columns]

In [170]:
for i in range(1, 6, 2):
    data_2['Cкользящая статистика ' + str(i) + ' mean'] = data_2.groupby('weekday')['CLOSE'].transform(
        lambda x: x.rolling(window=i).mean().shift(1))
    data_2['Cкользящая статистика ' + str(i) + ' median'] = data_2.groupby('weekday')['CLOSE'].transform(
        lambda x: x.rolling(window=i).median().shift(1))
    data_2['Cкользящая статистика ' + str(i) + ' max'] = data_2.groupby('weekday')['CLOSE'].transform(
        lambda x: x.rolling(window=i).max().shift(1))
    data_2['Cкользящая статистика ' + str(i) + ' min'] = data_2.groupby('weekday')['CLOSE'].transform(
        lambda x: x.rolling(window=i).min().shift(1))
    if i == 1:
        continue
    data_2['Cкользящая статистика ' + str(i) + ' std'] = data_2.groupby('weekday')['CLOSE'].transform(
        lambda x: x.rolling(window=i).std().shift(1))
data_2

,CLOSE,weekday,Лаг1,Лаг3,Лаг5,Лаг 1,Лаг 3,Лаг 5,Cкользящая статистика 1 mean,Cкользящая статистика 1 median,...,Cкользящая статистика 3 mean,Cкользящая статистика 3 median,Cкользящая статистика 3 max,Cкользящая статистика 3 min,Cкользящая статистика 3 std,Cкользящая статистика 5 mean,Cкользящая статистика 5 median,Cкользящая статистика 5 max,Cкользящая статистика 5 min,Cкользящая статистика 5 std
TRADEDATE,,,,,,,,,,,,,,,,,,,,,
2013-03-25,98.79,0,98.79,98.79,98.79,98.79,98.79,98.79,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2013-03-26,97.20,1,97.20,97.20,97.20,97.20,97.20,97.20,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2013-03-27,96.75,2,96.75,96.75,96.75,96.75,96.75,96.75,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2013-03-28,98.59,3,98.59,98.59,98.59,98.59,98.59,98.59,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2013-03-29,98.76,4,98.76,98.76,98.76,98.76,98.76,98.76,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-01-06,253.90,0,253.90,253.90,253.90,253.90,253.90,253.90,254.75,254.75,...,248.333333,248.80,254.75,241.45,6.662269,243.162,241.45,254.75,233.77,8.583244
2020-01-07,253.90,1,253.90,253.90,253.90,253.90,253.90,253.90,254.75,254.75,...,248.340000,248.67,254.75,241.60,6.581208,242.718,241.60,254.75,230.66,9.353575
2020-01-08,259.15,2,259.15,259.15,259.15,259.15,259.15,259.15,254.75,254.75,...,249.663333,248.04,254.75,246.20,4.500226,244.180,246.20,254.75,231.59,8.719412
2020-01-09,257.99,3,257.99,257.99,257.99,257.99,257.99,257.99,254.75,254.75,...,248.996667,248.24,254.75,244.00,5.414798,243.950,244.00,254.75,231.71,8.562625
2020-01-10,258.19,4,258.19,258.19,258.19,258.19,258.19,258.19,255.00,255.00,...,250.590000,252.06,255.00,244.71,5.300160,245.624,244.71,255.00,235.14,8.055503

In [171]:
data_2['праздник'] = Work_calendar.loc['2013-03-25':'2020-01-10']['праздник']
data_2['предпраздничный рабочий день'] = Work_calendar.loc[min(data_2.index):max(data_2.index)]['предпраздничный рабочий день']
data_2['рабочий день'] = np.zeros(len(data_2), dtype=int)
data_2.loc[(data_2['праздник'] == 0), ['рабочий день']] = 1
data_2

,CLOSE,weekday,Лаг1,Лаг3,Лаг5,Лаг 1,Лаг 3,Лаг 5,Cкользящая статистика 1 mean,Cкользящая статистика 1 median,...,Cкользящая статистика 3 min,Cкользящая статистика 3 std,Cкользящая статистика 5 mean,Cкользящая статистика 5 median,Cкользящая статистика 5 max,Cкользящая статистика 5 min,Cкользящая статистика 5 std,праздник,предпраздничный рабочий день,рабочий день
TRADEDATE,,,,,,,,,,,,,,,,,,,,,
2013-03-25,98.79,0,98.79,98.79,98.79,98.79,98.79,98.79,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1
2013-03-26,97.20,1,97.20,97.20,97.20,97.20,97.20,97.20,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1
2013-03-27,96.75,2,96.75,96.75,96.75,96.75,96.75,96.75,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1
2013-03-28,98.59,3,98.59,98.59,98.59,98.59,98.59,98.59,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1
2013-03-29,98.76,4,98.76,98.76,98.76,98.76,98.76,98.76,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-01-06,253.90,0,253.90,253.90,253.90,253.90,253.90,253.90,254.75,254.75,...,241.45,6.662269,243.162,241.45,254.75,233.77,8.583244,1,0,0
2020-01-07,253.90,1,253.90,253.90,253.90,253.90,253.90,253.90,254.75,254.75,...,241.60,6.581208,242.718,241.60,254.75,230.66,9.353575,1,0,0
2020-01-08,259.15,2,259.15,259.15,259.15,259.15,259.15,259.15,254.75,254.75,...,246.20,4.500226,244.180,246.20,254.75,231.59,8.719412,1,0,0
2020-01-09,257.99,3,257.99,257.99,257.99,257.99,257.99,257.99,254.75,254.75,...,244.00,5.414798,243.950,244.00,254.75,231.71,8.562625,0,0,1
2020-01-10,258.19,4,258.19,258.19,258.19,258.19,258.19,258.19,255.00,255.00,...,244.71,5.300160,245.624,244.71,255.00,235.14,8.055503,0,0,1

In [172]:
for i in ['праздник', 'рабочий день', 'предпраздничный рабочий день']:
    data_2['Expand. ' + str(i) + ' mean'] = data_2[data_2[i] == 1].CLOSE.expanding().mean()
    data_2['Expand. ' + str(i) + ' median'] = data_2[data_2[i] == 1].CLOSE.expanding().median()
    data_2['Expand. ' + str(i) + ' max'] = data_2[data_2[i] == 1].CLOSE.expanding().max()
    data_2['Expand. ' + str(i) + ' min'] = data_2[data_2[i] == 1].CLOSE.expanding().min()
    data_2['Expand. ' + str(i) + ' std'] = data_2[data_2[i] == 1].CLOSE.expanding().std()
print('Праздничный день')
print(data_2.loc['2013-05-01'])

Праздничный день
CLOSE                                           99.300000
weekday                                          2.000000
Лаг1                                            99.300000
Лаг3                                            99.300000
Лаг5                                            99.300000
Лаг 1                                           99.300000
Лаг 3                                           99.300000
Лаг 5                                           99.300000
Cкользящая статистика 1 mean                    97.890000
Cкользящая статистика 1 median                  97.890000
Cкользящая статистика 1 max                     97.890000
Cкользящая статистика 1 min                     97.890000
Cкользящая статистика 3 mean                    97.676667
Cкользящая статистика 3 median                  97.890000
Cкользящая статистика 3 max                    100.560000
Cкользящая статистика 3 min                     94.580000
Cкользящая статистика 3 std                      2.995702
Cкользящая статистика 5 mean                    97.874000
Cкользящая статистика 5 median                  97.890000
Cкользящая статистика 5 max                    100.560000
Cкользящая статистика 5 min                     94.580000
Cкользящая статистика 5 std                      2.359731
праздник                                         1.000000
предпраздничный рабочий день                     0.000000
рабочий день                                     0.000000
Expand. праздник mean                           99.300000
Expand. праздник median                         99.300000
Expand. праздник max                            99.300000
Expand. праздник min                            99.300000
Expand. праздник std                                  NaN
Expand. рабочий день mean                             NaN
Expand. рабочий день median                           NaN
Expand. рабочий день max                              NaN
Expand. рабочий день min                              NaN
Expand. рабочий день std                              NaN
Expand. предпраздничный рабочий день mean             NaN
Expand. предпраздничный рабочий день median           NaN
Expand. предпраздничный рабочий день max              NaN
Expand. предпраздничный рабочий день min              NaN
Expand. предпраздничный рабочий день std              NaN
Name: 2013-05-01 00:00:00, dtype: float64

In [173]:
print('Рабочий день')
print(data_2.loc['2020-01-10'])

Рабочий день
CLOSE                                          258.190000
weekday                                          4.000000
Лаг1                                           258.190000
Лаг3                                           258.190000
Лаг5                                           258.190000
Лаг 1                                          258.190000
Лаг 3                                          258.190000
Лаг 5                                          258.190000
Cкользящая статистика 1 mean                   255.000000
Cкользящая статистика 1 median                 255.000000
Cкользящая статистика 1 max                    255.000000
Cкользящая статистика 1 min                    255.000000
Cкользящая статистика 3 mean                   250.590000
Cкользящая статистика 3 median                 252.060000
Cкользящая статистика 3 max                    255.000000
Cкользящая статистика 3 min                    244.710000
Cкользящая статистика 3 std                      5.300160
Cкользящая статистика 5 mean                   245.624000
Cкользящая статистика 5 median                 244.710000
Cкользящая статистика 5 max                    255.000000
Cкользящая статистика 5 min                    235.140000
Cкользящая статистика 5 std                      8.055503
праздник                                         0.000000
предпраздничный рабочий день                     0.000000
рабочий день                                     1.000000
Expand. праздник mean                                 NaN
Expand. праздник median                               NaN
Expand. праздник max                                  NaN
Expand. праздник min                                  NaN
Expand. праздник std                                  NaN
Expand. рабочий день mean                      145.622283
Expand. рабочий день median                    139.450000
Expand. рабочий день max                       279.970000
Expand. рабочий день min                        53.500000
Expand. рабочий день std                        61.950842
Expand. предпраздничный рабочий день mean             NaN
Expand. предпраздничный рабочий день median           NaN
Expand. предпраздничный рабочий день max              NaN
Expand. предпраздничный рабочий день min              NaN
Expand. предпраздничный рабочий день std              NaN
Name: 2020-01-10 00:00:00, dtype: float64

In [174]:
print('Предпраздничный день')
print(data_2.loc['2019-02-22'])

Предпраздничный день
CLOSE                                          205.250000
weekday                                          4.000000
Лаг1                                           205.250000
Лаг3                                           205.250000
Лаг5                                           205.250000
Лаг 1                                          205.250000
Лаг 3                                          205.250000
Лаг 5                                          205.250000
Cкользящая статистика 1 mean                   208.000000
Cкользящая статистика 1 median                 208.000000
Cкользящая статистика 1 max                    208.000000
Cкользящая статистика 1 min                    208.000000
Cкользящая статистика 3 mean                   211.573333
Cкользящая статистика 3 median                 210.430000
Cкользящая статистика 3 max                    216.290000
Cкользящая статистика 3 min                    208.000000
Cкользящая статистика 3 std                      4.261623
Cкользящая статистика 5 mean                   211.032000
Cкользящая статистика 5 median                 210.430000
Cкользящая статистика 5 max                    216.290000
Cкользящая статистика 5 min                    208.000000
Cкользящая статистика 5 std                      3.348786
праздник                                         0.000000
предпраздничный рабочий день                     1.000000
рабочий день                                     1.000000
Expand. праздник mean                                 NaN
Expand. праздник median                               NaN
Expand. праздник max                                  NaN
Expand. праздник min                                  NaN
Expand. праздник std                                  NaN
Expand. рабочий день mean                      133.019360
Expand. рабочий день median                    108.510000
Expand. рабочий день max                       279.970000
Expand. рабочий день min                        53.500000
Expand. рабочий день std                        56.177377
Expand. предпраздничный рабочий день mean      140.449200
Expand. предпраздничный рабочий день median    102.390000
Expand. предпраздничный рабочий день max       277.490000
Expand. предпраздничный рабочий день min        72.500000
Expand. предпраздничный рабочий день std        66.498400
Name: 2019-02-22 00:00:00, dtype: float64